services:
  primary:
    image: postgres:latest
    container_name: primary
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    volumes:
      - ./primary:/var/lib/postgresql/data
    command: >
      postgres
      -c wal_level=replica
      -c max_wal_senders=10
      -c max_replication_slots=10
    ports:
      - 5432:5432

  replica:
    image: postgres:latest
    container_name: replica
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    volumes:
      - ./replica:/var/lib/postgresql/data
    ports:
      - 5433:5432
    depends_on:
      - primary
